# /robot_0/teleop_twist_joy_node:
/**:  # over all namespaces
  ros__parameters:
    axis_linear:
      x: 1              
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.4

    enable_button: 5        # RB
    enable_turbo_button: 4  # LB